-- =============================================================================
-- 01 - SCHEMAS (Estructura)
-- Incluye: configuración, tablas, identity, defaults y constraints (FK)
-- =============================================================================

-- =============================================================================
-- CONFIGURACIÓN INICIAL
-- =============================================================================
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';
SET default_table_access_method = heap;

-- =============================================================================
-- TABLAS
-- =============================================================================

-- =============================================================================
-- 01 - SCHEMA (GEOGRAFÍA)
-- PAÍS -> DEPARTAMENTO -> DISTRITO -> LOCALIDAD
-- =============================================================================

-- PAISES: lista de países
CREATE TABLE IF NOT EXISTS public.paises (
    id_pais bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre character varying(100) NOT NULL UNIQUE,
    iso2 char(2) UNIQUE,
    iso3 char(3) UNIQUE,
    activo boolean DEFAULT true NOT NULL
);

-- DEPARTAMENTOS: agrupación territorial dentro de un país
CREATE TABLE IF NOT EXISTS public.departamentos (
    id_departamento bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pais bigint NOT NULL,
    nombre character varying(120) NOT NULL UNIQUE,
    activo boolean DEFAULT true NOT NULL,
    CONSTRAINT departamentos_id_pais_fkey
        FOREIGN KEY (id_pais) REFERENCES public.paises(id_pais)
);

-- DISTRITOS: división territorial dentro de un departamento
CREATE TABLE IF NOT EXISTS public.distritos (
    id_distrito bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_departamento bigint NOT NULL,
    nombre character varying(120) NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    CONSTRAINT distritos_id_departamento_fkey
        FOREIGN KEY (id_departamento) REFERENCES public.departamentos(id_departamento),
    CONSTRAINT distritos_unique_departamento_nombre
        UNIQUE (id_departamento, nombre)
);

-- LOCALIDADES: barrios/zona/localidad dentro de un distrito
CREATE TABLE IF NOT EXISTS public.localidades (
    id_localidad bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_distrito bigint NOT NULL,
    nombre character varying(120) NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    CONSTRAINT localidades_id_distrito_fkey
        FOREIGN KEY (id_distrito) REFERENCES public.distritos(id_distrito),
    CONSTRAINT localidades_unique_distrito_nombre
        UNIQUE (id_distrito, nombre)
);

-- =============================================================================
-- CLIENTES
-- =============================================================================

-- CLIENTES: tabla base de clientes
CREATE TABLE IF NOT EXISTS public.clientes (
    id_cliente bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telefono character varying(30),
    email character varying(100),
    direccion character varying(255),
    id_distrito bigint,
    id_localidad bigint,
    activo boolean DEFAULT true NOT NULL,
    fecha_creacion timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT clientes_id_distrito_fkey
        FOREIGN KEY (id_distrito) REFERENCES public.distritos(id_distrito),
    CONSTRAINT clientes_id_localidad_fkey
        FOREIGN KEY (id_localidad) REFERENCES public.localidades(id_localidad)
);

-- CLIENTES PERSONA: datos específicos de personas
CREATE TABLE IF NOT EXISTS public.clientes_persona (
    id_cliente bigint PRIMARY KEY,
    nombre character varying(120) NOT NULL,
    apellido character varying(120) NOT NULL,
    apodo character varying(30),
    activo boolean DEFAULT true NOT NULL,
    CONSTRAINT clientes_persona_id_cliente_fkey
        FOREIGN KEY (id_cliente) REFERENCES public.clientes(id_cliente)
);

-- CLIENTES EMPRESA: datos específicos de empresas
CREATE TABLE IF NOT EXISTS public.clientes_empresa (
    id_cliente bigint PRIMARY KEY,
    razon_social character varying(255) NOT NULL,
    nombre_fantasia character varying(50),
    activo boolean DEFAULT true NOT NULL,
    CONSTRAINT clientes_empresa_id_cliente_fkey
        FOREIGN KEY (id_cliente) REFERENCES public.clientes(id_cliente)
);

-- =============================================================================
-- TIPOS DE DOCUMENTO / DOCUMENTOS CLIENTE
-- =============================================================================

-- TIPOS DE DOCUMENTO: DNI, RUC, pasaporte, etc.
CREATE TABLE IF NOT EXISTS public.tipos_documento (
    id_tipo_documento bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo character varying(20) NOT NULL UNIQUE,
    nombre character varying(120) NOT NULL,
    aplica_a character varying(10) NOT NULL,
    activo boolean DEFAULT true NOT NULL
);

-- DOCUMENTOS DE CLIENTES: puede tener varios, con indicador de principal
CREATE TABLE IF NOT EXISTS public.cliente_documentos (
    id_cliente_documento bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente bigint NOT NULL,
    id_tipo_documento bigint NOT NULL,
    numero character varying(40) NOT NULL,
    principal boolean DEFAULT false NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    CONSTRAINT cliente_documentos_id_cliente_fkey
        FOREIGN KEY (id_cliente) REFERENCES public.clientes(id_cliente),
    CONSTRAINT cliente_documentos_id_tipo_documento_fkey
        FOREIGN KEY (id_tipo_documento) REFERENCES public.tipos_documento(id_tipo_documento)
);

-- =============================================================================
-- MARCAS / MODELOS
-- =============================================================================

-- MARCAS: marcas de vehículos o componentes
CREATE TABLE IF NOT EXISTS public.marcas (
    id_marca bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre character varying(50) NOT NULL UNIQUE,
    activo boolean DEFAULT true NOT NULL
);

-- MODELOS: modelos asociados a marcas
CREATE TABLE IF NOT EXISTS public.modelos (
    id_modelo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_marca bigint NOT NULL,
    nombre character varying(50) NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    CONSTRAINT modelos_id_marca_fkey
        FOREIGN KEY (id_marca) REFERENCES public.marcas(id_marca),
    CONSTRAINT modelos_unique_marca_nombre
        UNIQUE (id_marca, nombre)
);

-- VEHÍCULOS: vehículos de clientes
CREATE TABLE IF NOT EXISTS public.vehiculos (
    id_vehiculo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente bigint NOT NULL,
    placa character varying(20) NOT NULL UNIQUE,
    id_marca bigint NOT NULL,
    id_modelo bigint,
    anio smallint,
    tipo_vehiculo character varying(20) NOT NULL,
    observaciones character varying(255),
    activo boolean DEFAULT true NOT NULL,
    CONSTRAINT vehiculos_id_cliente_fkey
        FOREIGN KEY (id_cliente) REFERENCES public.clientes(id_cliente),
    CONSTRAINT vehiculos_id_marca_fkey
        FOREIGN KEY (id_marca) REFERENCES public.marcas(id_marca),
    CONSTRAINT vehiculos_id_modelo_fkey
        FOREIGN KEY (id_modelo) REFERENCES public.modelos(id_modelo)
);

-- COMPONENTES: piezas traídas sin vehículo
CREATE TABLE IF NOT EXISTS public.componentes (
    id_componente bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente bigint NOT NULL,
    tipo_componente character varying(50) NOT NULL,
    id_marca bigint NOT NULL,
    id_modelo bigint NOT NULL,
    cantidad integer NOT NULL DEFAULT 1,
    observaciones character varying(255),
    activo boolean DEFAULT true NOT NULL,
    CONSTRAINT componentes_id_cliente_fkey
        FOREIGN KEY (id_cliente) REFERENCES public.clientes (id_cliente),
    CONSTRAINT componentes_id_marca_fkey
        FOREIGN KEY (id_marca) REFERENCES public.marcas (id_marca),
    CONSTRAINT componentes_id_modelo_fkey
        FOREIGN KEY (id_modelo) REFERENCES public.modelos (id_modelo)
);

-- =============================================================================
-- SERVICIOS
-- =============================================================================

-- SERVICIOS: trabajos ofrecidos en el taller
CREATE TABLE IF NOT EXISTS public.servicios (
    id_servicio bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo character varying(20) NOT NULL UNIQUE,
    nombre character varying(120) NOT NULL,
    descripcion character varying(255),
    precio_base numeric(14,0) DEFAULT 0 NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    fecha_creacion timestamp without time zone DEFAULT now() NOT NULL
);

-- =============================================================================
-- ROLES / PERMISOS / ROLES_PERMISOS
-- =============================================================================

-- ROLES: catálogo de roles del sistema
CREATE TABLE IF NOT EXISTS public.roles (
    id_rol bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo character varying(50) NOT NULL UNIQUE,
    nombre character varying(120) NOT NULL,
    descripcion character varying(255),
    activo boolean DEFAULT true NOT NULL,
    fecha_creacion timestamp without time zone DEFAULT now() NOT NULL
);

-- PERMISOS: catálogo de permisos/acciones del sistema
CREATE TABLE IF NOT EXISTS public.permisos (
    id_permiso bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo character varying(80) NOT NULL UNIQUE,
    nombre character varying(120) NOT NULL,
    descripcion character varying(255),
    activo boolean DEFAULT true NOT NULL,
    fecha_creacion timestamp without time zone DEFAULT now() NOT NULL
);

-- ROLES_PERMISOS: permisos asociados a cada rol (N:M)
CREATE TABLE IF NOT EXISTS public.roles_permisos (
    id_rol bigint NOT NULL,
    id_permiso bigint NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    fecha_creacion timestamp without time zone DEFAULT now() NOT NULL,
    PRIMARY KEY (id_rol, id_permiso),
    CONSTRAINT roles_permisos_id_rol_fkey
        FOREIGN KEY (id_rol) REFERENCES public.roles(id_rol) ON DELETE CASCADE,
    CONSTRAINT roles_permisos_id_permiso_fkey
        FOREIGN KEY (id_permiso) REFERENCES public.permisos(id_permiso) ON DELETE CASCADE
);

-- =============================================================================
-- USUARIOS
-- =============================================================================

-- USUARIOS: empleados o responsables de las OT
CREATE TABLE IF NOT EXISTS public.usuarios (
    id_usuario bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rol bigint NOT NULL,
    nombre character varying(50) NOT NULL,
    apellido character varying(50) NOT NULL,
    nombre_usuario character varying(50) NOT NULL UNIQUE,
    email character varying(100) NOT NULL UNIQUE,
    password_hash character varying(255) NOT NULL,
    id_tipo_documento bigint NOT NULL,
    numero_documento character varying(40) NOT NULL,
    fecha_nacimiento date,
    activo boolean DEFAULT true NOT NULL,
    fecha_creacion timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT usuarios_id_tipo_documento_fkey
        FOREIGN KEY (id_tipo_documento) REFERENCES public.tipos_documento(id_tipo_documento),
    CONSTRAINT usuarios_id_rol_fkey
        FOREIGN KEY (id_rol) REFERENCES public.roles(id_rol)
);

-- =============================================================================
-- ORDENES_TRABAJO
-- Nota: Requiere enums ya creados:
--   public.tipo_ingreso_orden_enum
--   public.estado_orden_trabajo_enum
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.ordenes_trabajo (
    id_orden_trabajo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_orden character varying(30) NOT NULL UNIQUE, -- generado desde 03_Post
    id_usuario bigint NOT NULL,
    id_cliente bigint NOT NULL,
    tipo_ingreso public.tipo_ingreso_orden_enum NOT NULL,
    id_vehiculo bigint,
    id_componente bigint,
    fecha_ingreso timestamp without time zone DEFAULT now() NOT NULL,
    problema_reportado character varying(255),
    observaciones_ingreso character varying(255),
    estado public.estado_orden_trabajo_enum NOT NULL,
    fecha_entrega timestamp without time zone,
    total_estimado numeric(14,0) DEFAULT 0 NOT NULL,
    fecha_fin timestamp without time zone,
    activo boolean DEFAULT true NOT NULL,
    fecha_creacion timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT ordenes_trabajo_id_usuario_fkey
        FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario),
    CONSTRAINT ordenes_trabajo_id_cliente_fkey
        FOREIGN KEY (id_cliente) REFERENCES public.clientes(id_cliente),
    CONSTRAINT ordenes_trabajo_id_vehiculo_fkey
        FOREIGN KEY (id_vehiculo) REFERENCES public.vehiculos(id_vehiculo),
    CONSTRAINT ordenes_trabajo_id_componente_fkey
        FOREIGN KEY (id_componente) REFERENCES public.componentes(id_componente)
);

-- =============================================================================
-- DETALLES DE ORDEN
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.orden_trabajo_detalles (
    id_detalle bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_orden_trabajo bigint NOT NULL,
    id_servicio bigint NOT NULL,
    descripcion character varying(255),
    cantidad integer NOT NULL DEFAULT 1,
    precio_unitario numeric(14,0),
    subtotal numeric(14,0) GENERATED ALWAYS AS (cantidad * precio_unitario) STORED,
    observaciones character varying(255),
    garantia_meses smallint,
    garantia_dias smallint,
    garantia_desde date,
    garantia_hasta date,
    activo boolean DEFAULT true NOT NULL,
    fecha_creacion timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT orden_trabajo_detalles_id_orden_trabajo_fkey
        FOREIGN KEY (id_orden_trabajo) REFERENCES public.ordenes_trabajo(id_orden_trabajo),
    CONSTRAINT orden_trabajo_detalles_id_servicio_fkey
        FOREIGN KEY (id_servicio) REFERENCES public.servicios(id_servicio)
);

-- =============================================================================
-- PLANES DE PAGO
-- Nota: Requiere enums ya creados:
--   public.tipo_plan_pago_enum
--   public.estado_plan_pago_enum
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.planes_pago (
    id_plan_pago bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_orden_trabajo bigint NOT NULL,
    tipo_plan public.tipo_plan_pago_enum NOT NULL,
    estado public.estado_plan_pago_enum NOT NULL,
    fecha_inicio date DEFAULT CURRENT_DATE,
    fecha_vencimiento date,
    monto_cuota numeric(14,0) DEFAULT 0 NOT NULL,
    dia_pago smallint,
    cantidad_cuotas smallint DEFAULT 1 NOT NULL,
    observaciones character varying(255),
    activo boolean DEFAULT true NOT NULL,
    fecha_creacion timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT planes_pago_id_orden_trabajo_fkey
        FOREIGN KEY (id_orden_trabajo) REFERENCES public.ordenes_trabajo(id_orden_trabajo)
);

-- =============================================================================
-- EVENTOS DE PLAN
-- Nota: Requiere enum ya creado:
--   public.tipo_evento_plan_pago_enum
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.planes_pago_eventos (
    id_evento bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_plan_pago bigint NOT NULL,
    fecha_evento timestamp without time zone DEFAULT now() NOT NULL,
    tipo_evento public.tipo_evento_plan_pago_enum NOT NULL,
    fecha_compromiso date,
    monto_compromiso numeric(14,0),
    detalle character varying(255),
    activo boolean DEFAULT true NOT NULL,
    CONSTRAINT planes_pago_eventos_id_plan_pago_fkey
        FOREIGN KEY (id_plan_pago) REFERENCES public.planes_pago(id_plan_pago)
);

-- =============================================================================
-- PAGOS
-- Nota: Requiere enum ya creado:
--   public.forma_pago_enum
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.pagos (
    id_pago bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario bigint NOT NULL,
    id_orden_trabajo bigint NOT NULL,
    id_plan_pago bigint,
    fecha_pago timestamp without time zone DEFAULT now() NOT NULL,
    monto numeric(14,0) DEFAULT 0 NOT NULL,
    forma_pago public.forma_pago_enum NOT NULL,
    referencia character varying(80),
    observaciones character varying(255),
    activo boolean DEFAULT true NOT NULL,
    fecha_creacion timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT pagos_id_usuario_fkey
        FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario),
    CONSTRAINT pagos_id_orden_trabajo_fkey
        FOREIGN KEY (id_orden_trabajo) REFERENCES public.ordenes_trabajo(id_orden_trabajo),
    CONSTRAINT pagos_id_plan_pago_fkey
        FOREIGN KEY (id_plan_pago) REFERENCES public.planes_pago(id_plan_pago)
);

-- =============================================================================
-- OWNER - PROPIETARIO DE OBJETOS
-- =============================================================================

-- Geografía
ALTER TABLE IF EXISTS public.paises OWNER TO postgres;
ALTER TABLE IF EXISTS public.departamentos OWNER TO postgres;
ALTER TABLE IF EXISTS public.distritos OWNER TO postgres;
ALTER TABLE IF EXISTS public.localidades OWNER TO postgres;

-- Clientes y Documentos
ALTER TABLE IF EXISTS public.clientes OWNER TO postgres;
ALTER TABLE IF EXISTS public.clientes_persona OWNER TO postgres;
ALTER TABLE IF EXISTS public.clientes_empresa OWNER TO postgres;
ALTER TABLE IF EXISTS public.tipos_documento OWNER TO postgres;
ALTER TABLE IF EXISTS public.cliente_documentos OWNER TO postgres;

-- Activos del Taller (Vehículos y Componentes)
ALTER TABLE IF EXISTS public.marcas OWNER TO postgres;
ALTER TABLE IF EXISTS public.modelos OWNER TO postgres;
ALTER TABLE IF EXISTS public.vehiculos OWNER TO postgres;
ALTER TABLE IF EXISTS public.componentes OWNER TO postgres;
ALTER TABLE IF EXISTS public.servicios OWNER TO postgres;

-- Usuarios y Operaciones
ALTER TABLE IF EXISTS public.roles OWNER TO postgres;
ALTER TABLE IF EXISTS public.permisos OWNER TO postgres;
ALTER TABLE IF EXISTS public.roles_permisos OWNER TO postgres;
ALTER TABLE IF EXISTS public.usuarios OWNER TO postgres;
ALTER TABLE IF EXISTS public.ordenes_trabajo OWNER TO postgres;
ALTER TABLE IF EXISTS public.orden_trabajo_detalles OWNER TO postgres;

-- Finanzas (Planes y Pagos)
ALTER TABLE IF EXISTS public.planes_pago OWNER TO postgres;
ALTER TABLE IF EXISTS public.planes_pago_eventos OWNER TO postgres;
ALTER TABLE IF EXISTS public.pagos OWNER TO postgres;

-- =============================================================================
-- FIN DEL SCRIPT 01_SCHEMA
-- =============================================================================
